<?php

return [
    1 => [
        'gradient' => '#22c55e',
        'badge_color' => 'green',
        'welcome_title' => 'Bienvenue dans votre aventure !',
        'welcome_message' => 'Découvrez votre tableau de bord et commencez à bâtir votre réseau.',
        'show_chart' => true,
        'show_leaders' => false,
        'show_max_banner' => false,
        'quick_actions' => ['packages', 'products', 'withdrawal', 'team'],
    ],
    2 => [
        'gradient' => '#3b82f6',
        'badge_color' => 'blue',
        'welcome_title' => 'Continuez votre progression !',
        'welcome_message' => 'Votre réseau grandit, maintenez le rythme.',
        'show_chart' => true,
        'show_leaders' => false,
        'show_max_banner' => false,
        'quick_actions' => ['packages', 'products', 'withdrawal', 'team'],
    ],
    3 => [
        'gradient' => '#f59e0b',
        'badge_color' => 'amber',
        'welcome_title' => 'Bon travail !',
        'welcome_message' => 'Votre réseau se développe, vous progressez.',
        'show_chart' => true,
        'show_leaders' => true,
        'show_max_banner' => false,
        'quick_actions' => ['packages', 'products', 'withdrawal', 'team'],
    ],
    4 => [
        'gradient' => '#8b5cf6',
        'badge_color' => 'purple',
        'welcome_title' => 'Niveau supérieur atteint !',
        'welcome_message' => 'Vous êtes maintenant un leader confirmé.',
        'show_chart' => true,
        'show_leaders' => true,
        'show_max_banner' => false,
        'quick_actions' => ['network', 'commissions', 'wallet', 'grades'],
    ],
    5 => [
        'gradient' => '#eab308',
        'badge_color' => 'yellow',
        'welcome_title' => 'Niveau Or atteint !',
        'welcome_message' => 'Votre leadership inspire votre équipe.',
        'show_chart' => true,
        'show_leaders' => true,
        'show_max_banner' => false,
        'quick_actions' => ['network', 'commissions', 'wallet', 'grades'],
    ],
    6 => [
        'gradient' => '#9333ea',
        'badge_color' => 'purple',
        'welcome_title' => 'Niveau Élite !',
        'welcome_message' => 'Vous faites partie des meilleurs.',
        'show_chart' => true,
        'show_leaders' => false,
        'show_max_banner' => false,
        'quick_actions' => ['packages', 'products', 'withdrawal', 'team'],
    ],
    7 => [
        'gradient' => '#ec4899',
        'badge_color' => 'pink',
        'welcome_title' => 'Niveau Rose !',
        'welcome_message' => 'Vous êtes une référence dans votre réseau.',
        'show_chart' => true,
        'show_leaders' => true,
        'show_max_banner' => false,
        'quick_actions' => ['network', 'commissions', 'wallet', 'grades'],
    ],
    8 => [
        'gradient' => '#06b6d4',
        'badge_color' => 'cyan',
        'welcome_title' => 'Niveau Cyan !',
        'welcome_message' => 'Votre influence s\'étend.',
        'show_chart' => true,
        'show_leaders' => true,
        'show_max_banner' => false,
        'quick_actions' => ['network', 'commissions', 'wallet', 'grades'],
    ],
    9 => [
        'gradient' => '#f43f5e',
        'badge_color' => 'rose',
        'welcome_title' => 'Niveau Perle Diamant !',
        'welcome_message' => 'Vous avez atteint le sommet. Félicitations !',
        'show_chart' => true,
        'show_leaders' => true,
        'show_max_banner' => true,
        'quick_actions' => ['network', 'commissions', 'wallet', 'grades'],
    ],
];
