<?php

return [
    'max_results' => 8,
    'max_query_length' => 200,

    'quick_prompts' => [
        'Mon solde',
        'Faire un retrait',
        'Comprendre les PV',
        'KYC',
        'Parrainage',
        'Commissions',
    ],

    'articles' => [
        [
            'id' => 'wallet-balance',
            'title' => 'Solde et portefeuille',
            'keywords' => ['solde', 'portefeuille', 'wallet', 'argent', 'usd', 'disponible', 'fonds'],
            'answer' => 'Votre solde disponible est de :balance USD. Consultez l’historique des mouvements (commissions, dépôts, retraits, achats) depuis le portefeuille.',
            'dynamic' => true,
            'route' => 'wallet.index',
            'route_label' => 'Mon portefeuille',
        ],
        [
            'id' => 'deposit',
            'title' => 'Dépôt de fonds',
            'keywords' => ['dépôt', 'depot', 'alimenter', 'créditer', 'crypto', 'mobile money', 'virement'],
            'answer' => 'Les dépôts se font depuis « Dépôt » : crypto, Mobile Money ou virement. Frais : 0 %. Montant minimum 1 USD, maximum 10 000 USD par opération.',
            'route' => 'wallet.deposit',
            'route_label' => 'Faire un dépôt',
        ],
        [
            'id' => 'withdrawal',
            'title' => 'Retrait de gains',
            'keywords' => ['retrait', 'retirer', 'retrait', 'frais', '2.5', 'plafond', 'limite'],
            'answer' => 'Demandez un retrait vers crypto, Mobile Money ou banque. Frais : 2,5 %. Minimum 10 USD. Plafond journalier 5 000 USD (demandes en attente). Au-delà de 5 000 USD cumulés retirés, le KYC vérifié est requis.',
            'route' => 'withdrawal.index',
            'route_label' => 'Demander un retrait',
        ],
        [
            'id' => 'commissions',
            'title' => 'Commissions et gains',
            'keywords' => ['commission', 'gains', 'bonus', 'rémunération', 'niveau', 'direct', 'indirect'],
            'answer' => 'Vos commissions (direct, indirect, leadership, etc.) sont listées dans « Mes commissions » et le tableau de bord. Seules les commissions versées alimentent vos totaux officiels.',
            'route' => 'commissions.index',
            'route_label' => 'Mes commissions',
        ],
        [
            'id' => 'pv',
            'title' => 'PV et volume',
            'keywords' => ['pv', 'volume', 'bv', 'points', 'qualification', 'grade', 'rang'],
            'answer' => 'Les PV (points volume) suivent vos achats et l’activité du réseau. Votre PV personnel affiché : :personal_pv. Suivez l’historique et les périodes dans « Mes PV ».',
            'dynamic' => true,
            'route' => 'my-pv.index',
            'route_label' => 'Mes PV',
        ],
        [
            'id' => 'rank',
            'title' => 'Grade et progression',
            'keywords' => ['grade', 'rang', 'rank', 'qualification', 'distributeur', 'directeur', 'diamant'],
            'answer' => 'Votre grade actuel : :rank_name. La progression depend des PV/BV et de la structure d’équipe. Consultez la page « Mon grade » pour les conditions du prochain palier.',
            'dynamic' => true,
            'route' => 'rank.index',
            'route_label' => 'Mon grade',
        ],
        [
            'id' => 'network',
            'title' => 'Réseau et filleuls',
            'keywords' => ['réseau', 'filleul', 'parrain', 'downline', 'équipe', 'arbre', 'binaire'],
            'answer' => 'Visualisez votre arbre, vos filleuls directs et l’activité du réseau dans « Mon réseau ». Partagez votre lien ou code parrain depuis le profil.',
            'route' => 'network.index',
            'route_label' => 'Mon réseau',
        ],
        [
            'id' => 'referral',
            'title' => 'Parrainage et inscription',
            'keywords' => ['parrain', 'parrainage', 'code', 'lien', 'inviter', 'inscription', 'adhésion', '30 usd'],
            'answer' => 'Chaque nouveau membre a besoin d’un code parrain. L’adhésion est de 30 USD (unique). Copiez votre lien de parrainage dans « Profil » → « Parrainage ».',
            'route' => 'profile.referral',
            'route_label' => 'Mon lien parrain',
        ],
        [
            'id' => 'kyc',
            'title' => 'Vérification KYC',
            'keywords' => ['kyc', 'identité', 'vérification', 'pièce', 'document', 'verified'],
            'answer' => 'Statut KYC : :kyc_label. La vérification est obligatoire pour retirer des montants importants (seuil cumulé 5 000 USD). Déposez vos documents dans « Vérification d’identité ».',
            'dynamic' => true,
            'route' => 'kyc.index',
            'route_label' => 'Vérification KYC',
        ],
        [
            'id' => 'orders',
            'title' => 'Commandes boutique',
            'keywords' => ['commande', 'achat', 'boutique', 'produit', 'livraison', 'panier'],
            'answer' => 'Passez commande depuis la boutique ou le panier. Suivez le statut dans « Mes commandes ».',
            'route' => 'orders.index',
            'route_label' => 'Mes commandes',
        ],
        [
            'id' => 'packages',
            'title' => 'Packages',
            'keywords' => ['package', 'abonnement', 'formule', 'upgrade'],
            'answer' => 'Les packages membre donnent accès à des volumes ou avantages spécifiques. Consultez et achetez un package depuis la page « Packages ».',
            'route' => 'subscriptions.index',
            'route_label' => 'Packages',
        ],
        [
            'id' => 'reports',
            'title' => 'Rapports et exports',
            'keywords' => ['rapport', 'statistique', 'export', 'historique', 'pdf'],
            'answer' => 'Le hub « Rapports » regroupe accès aux historiques (portefeuille, retraits, commissions, PV) et à l’export du portefeuille.',
            'route' => 'report.index',
            'route_label' => 'Rapports',
        ],
        [
            'id' => 'activate',
            'title' => 'Activer mon compte',
            'keywords' => ['activer', 'activation', 'compte', 'bloqué', 'mot de passe'],
            'answer' => 'Si votre compte n’est pas encore actif ou si vous devez finaliser l’activation, utilisez « Activer mon compte » depuis l’aide.',
            'route' => 'activate.index',
            'route_label' => 'Activer mon compte',
        ],
        [
            'id' => 'contact',
            'title' => 'Contacter le support',
            'keywords' => ['contact', 'support', 'aide', 'humain', 'email', 'téléphone', 'problème'],
            'answer' => 'Pour une demande non couverte ici ou un litige, contactez Salang Group (coordonnées officielles sur la page « Nous contacter »).',
            'route' => 'contact',
            'route_label' => 'Nous contacter',
        ],
        [
            'id' => 'cart',
            'title' => 'Panier',
            'keywords' => ['panier', 'cart', 'checkout', 'payer'],
            'answer' => 'Ajoutez des produits à la boutique au panier, puis validez la commande. Le paiement utilise votre portefeuille ou les moyens proposés au checkout.',
            'route' => 'cart.index',
            'route_label' => 'Mon panier',
        ],
    ],
];
