<?php
// app/Http/Controllers/Admin/ActivationController.php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use App\Notifications\ActivationCodeNotification;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

class ActivationController extends Controller
{
    /**
     * Liste des utilisateurs inactifs
     */
    public function index()
    {
        $inactiveUsers = User::where('is_active', false)
            ->whereNotNull('activation_code')
            ->orderBy('created_at', 'desc')
            ->paginate(20);

        return view('admin.activations.index', compact('inactiveUsers'));
    }

    /**
     * Générer un code d'activation pour un utilisateur
     * ✅ ENVOI AUTOMATIQUE DE LA NOTIFICATION
     */
    public function generateCode($userId)
    {
        $user = User::findOrFail($userId);

        if ($user->is_active) {
            return back()->with('error', 'Ce compte est déjà actif.');
        }

        $code = 'ACT-' . strtoupper(substr(md5(uniqid() . time() . rand()), 0, 12));

        $user->update([
            'activation_code' => $code,
            'activation_code_expires_at' => now()->addDays(7),
        ]);

        // ✅ ENVOI AUTOMATIQUE DE LA NOTIFICATION
        try {
            $user->notify(new ActivationCodeNotification($code));
            
            Log::info('Code d\'activation généré et envoyé automatiquement', [
                'user_id' => $user->id,
                'user_email' => $user->email,
                'admin_id' => auth()->id(),
                'code' => $code,
            ]);
        } catch (\Exception $e) {
            Log::error('Erreur lors de l\'envoi du code d\'activation', [
                'user_id' => $user->id,
                'error' => $e->getMessage(),
            ]);
            // ✅ On continue même si l'email échoue
        }

        Log::info('Activation code generated by admin', [
            'user_id' => $user->id,
            'admin_id' => auth()->id(),
        ]);

        return back()->with('success', "Code d'activation généré et envoyé à {$user->email} : {$code}");
    }

    /**
     * Activer manuellement un utilisateur (admin)
     */
    public function activateManually($userId)
    {
        $user = User::findOrFail($userId);

        if ($user->is_active) {
            return back()->with('error', 'Ce compte est déjà actif.');
        }

        $user->update([
            'is_active' => true,
            'activated_at' => now(),
            'activation_method' => 'admin_manual',
            'activation_code' => null,
            'activation_code_expires_at' => null,
        ]);

        Log::info('User activated manually by admin', [
            'user_id' => $user->id,
            'admin_id' => auth()->id(),
        ]);

        return back()->with('success', "Compte de {$user->name} activé avec succès.");
    }

    /**
     * Envoyer un code d'activation par email
     * ✅ ENVOI AUTOMATIQUE
     */
    public function sendCode($userId)
    {
        $user = User::findOrFail($userId);

        if ($user->is_active) {
            return back()->with('error', 'Ce compte est déjà actif.');
        }

        if (!$user->activation_code) {
            return back()->with('error', 'Aucun code d\'activation généré pour cet utilisateur.');
        }

        // ✅ ENVOI AUTOMATIQUE
        try {
            $user->notify(new ActivationCodeNotification($user->activation_code));
            
            Log::info('Code d\'activation renvoyé automatiquement', [
                'user_id' => $user->id,
                'user_email' => $user->email,
                'admin_id' => auth()->id(),
            ]);
        } catch (\Exception $e) {
            Log::error('Erreur lors de l\'envoi du code d\'activation', [
                'user_id' => $user->id,
                'error' => $e->getMessage(),
            ]);
            return back()->with('error', 'Erreur lors de l\'envoi du code.');
        }

        return back()->with('success', "Code d'activation envoyé à {$user->email}");
    }
}